name: Check for "don't merge" label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check for "don't merge" label
        id: check_label
        run: |
          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          if echo "$labels" | grep -q "don't merge"; then
            echo "Pull request has 'don't merge' label. Failing the check."
            exit 1
          else
            echo "No 'don't merge' label found. Passing the check."
          fi

      - name: Set status
        if: ${{ failure() }}
        run: exit 1
